### ISSUE TITLE
Latest M.A.M.E. has new XML format - breaks ia-mame

### ISSUE THREAD

**Issue by intrepidsilence** [TiBeN/ia-mame#11]
The new XML format provided by M.A.M.E. breaks ia-mame.  I am not sure in which version of M.A.M.E. this started.

**Comment by TiBeN** [comment]
I'm pretty sure this is related to #10 . I've tested with mame v0.197 and it works well. XML format does not seems to have changed.

**Comment by TiBeN** [comment]
I close this issue. Please reopen if this error persists.
