### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by tekdope** [TiBeN/ia-mame#12]
I am having this message when I run IA-Mame.

java.lang.NoClassDefFoundError: javax/xml/bind/DataBindingException

Any solution or workaround?

**Comment by TiBeN** [comment]
Hi, 
It seems to be related to issue #10. I'm planning a maintenance release to fix this among other things asap. 

Thanks for report.

**Comment by TiBeN** [comment]
I confirm this issue is a duplicate of #10. I close this one. Please refers to #10. Thanks
