### ISSUE TITLE
"No writable path to write roms into" occurs whenever I try to download a rom

### ISSUE THREAD

**Issue by jadasse** [TiBeN/ia-mame#15]
Whenever I try to play a title, I get this error message: "No writable path to write roms into". I'm currently running on Windows 10 on command prompt btw. What should I do?

**Comment by TiBeN** [comment]
Do you have your rompath configured properly in your mame.ini ?
Some tips:
-  Type "mame64.exe -showconfig" to see where mame looks for roms (value of rompath parameter) and determine if the path 
   actually exists
-  Try bare mame with some roms to make sure mame is configured properly before trying to use ia-rcade
-  If the path specified in the mame configuration actually exists, make sure it is writable

**Comment by jadasse** [comment]
i figured it out
