### ISSUE TITLE
MAME version requirement should read 0.162+

### ISSUE THREAD

**Issue by nblondiau** [TiBeN/ia-mame#3]
The required version is 0.162+, not 0.161+, as the merge between MAME and MESS happened in  0.162.
0.161+ means >=0.161, not >0.161.

This project rocks, keep up the good work.

**Comment by TiBeN** [comment]
Hi, thank you for reporting this issue. 
You are right, this has been fixed in commit https://github.com/TiBeN/ia-mame/commit/ff79461b1c2370237996e2a66d762cb8ee94beb6
