### ISSUE TITLE
Small issue: Crash when using uppercase letters

### ISSUE THREAD

**Issue by geoffyuen** [TiBeN/ia-mame#5]
`ia-mame Gaplus`

Produces: 

> Exception in thread "main" java.lang.RuntimeException: Unhandled case: Mame returned no errors while searching for machine Gaplus but the machine has not been found on the XML content
>     at org.tibennetwork.iamame.mame.MachineRepository.findByName(MachineRepository.java:98)
>     at org.tibennetwork.iamame.mame.MameArguments.extractMachineAndSoftwares(MameArguments.java:265)
>     at org.tibennetwork.iamame.IaMame.downloadFilesIfNeeded(IaMame.java:173)
>     at org.tibennetwork.iamame.IaMame.main(IaMame.java:54)

`./mame64  Gaplus` runs ok.

**Comment by TiBeN** [comment]
Thanks for report. This has been fixed in commit 5f88f124e1f085a6599ff53435e4233e120a4e65
