### ISSUE TITLE
Java Exception on Debian 8

### ISSUE THREAD

**Issue by xaviervalarino** [TiBeN/ia-mame#8]
I have been running in to the same java exception while trying to run ia-mame

#### An example with the error message
```
$ ia-mame alien3
Exception in thread "main" java.lang.NullPointerException
	at org.tibennetwork.iamame.mame.MediaDevice.getBriefname(MediaDevice.java:35)
	at org.tibennetwork.iamame.CommandLineArguments.extractMachineAndSoftwares(CommandLineArguments.java:242)
	at org.tibennetwork.iamame.IaMame.downloadFilesIfNeeded(IaMame.java:187)
	at org.tibennetwork.iamame.IaMame.main(IaMame.java:76)
````

#### My environment
```
$ uname -svrm
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_6

$ java -version
java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-2~deb8u1)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

$ mame -help
MAME v0.180 (unknown)
```

**Comment by TiBeN** [comment]
Is the exception thrown with any system or with alien3 only ?

**Comment by xaviervalarino** [comment]
Actually, it looks like alien3 is not one of the offending ROMs.

Here is a list of ROMs that seem to have this issue:
```
2020bb
alpham2
bstars2
blazstar
fatfury1
kotm
magdrop3
mslug
mslug2
mslug3
mslug4
mslugx
nam1975
pgoal
pulstar
rbff2
samsho
samsho2
sengoku3
shocktro
socbrawl
tekken2
kof98
lastblad
lastbld2
superspy
viewpoin
wakuwak7
wjammers
```

I was running `mame -noexecmame` inside of a bash script, so I can't be certain, but checking the files against the original list returned these names.


Here is a gist of the scripts and data file (in case they are useful):
https://gist.github.com/xaviervalarino/8f7d2dccd87e7462aef69de51d9d4d88

**Comment by TiBeN** [comment]
Seems there is some changes on the XML metadata structure.
I am a little busy now, but i'll take a look at this issue asap. 
As a temporary workaround you can use an older mame version. Version 0.162 is recommended because it a closer match with archive collections.

**Comment by xaviervalarino** [comment]
Thanks! I'll try it out with 0.154 [(Debian packages for MAME jump from 0.154 to 0.180)](https://packages.debian.org/search?keywords=mame), and maybe also try to build 0.162 from source.

**Comment by TiBeN** [comment]
Ok but beware all the mess stuff have been combined from version 0.162 . It is not an issue if you only need the mame arcade stuff. You can use separate mess 0.154 too.

**Comment by TiBeN** [comment]
I close the issue. If you encounter this problem again don't hesitate to reopen it.
