### ISSUE TITLE
Enhancement request: Support MAME 0.185 romset

### ISSUE THREAD

**Issue by nblondiau** [TiBeN/ia-mame#9]
0.185 romset is up on archive.org:

https://archive.org/details/MAME_0.185_ROMs_split

**Comment by TiBeN** [comment]
Hi, 
This is implemented by 0d092b1d9476b363a41f12dc44453c0b3e4aa1f3
All archive.org romsets since 0.149 are now supported. ia-mame find and use the version matching the closest to your mame version.
